baseURL = "localhost:1313"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "AutomatizaciÃ³n que Transforma"

defaultContentLanguage = "es"
# language code ["en", "zh-CN", "fr", "pl", ...]
languageCode = "es"
# language name ["English", "ç®€ä½“ä¸­æ–‡", "FranÃ§ais", "Polski", ...]
languageName = "Spanish"
 
# Author config
[author]
  name = "Raymundo Ycaza"
  email = ""
  link = "https://linkedin.com/in/raymundoycaza"

[permalinks]
    pages = "/:slug/"
[taxonomies]
  category = 'categories'
  tags = 'tags'

[params]
  # site default theme ["auto", "light", "dark"]
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  gitRepo = ""
  # LoveIt NEW | 0.1.1 which hash function used for SRI, when empty, no SRI is used
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  # LoveIt NEW | 0.2.0 date format
  dateFormat = "2006-01-02"
  # website title for Open Graph and Twitter Cards
  title = "RY"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  description = "AutomatizaciÃ³n que Transforma"
  # website images for Open Graph and Twitter Cards
  images = ["/logo.png"]
 
   # Home page config
  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/avatar.png"
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = ""
      # subtitle shown in home page (HTML format is supported)
      subtitle = "AutomatizaciÃ³n que Transforma"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = false
      # special amount of posts in each home posts page
      paginate = 6
      # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "blog"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = "ðŸŽ‰"
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Blog"
    url = "/pages/automatizacion-excel/listar-auto-excel/"
    # title will be shown when you hover on this menu link
    title = "ArtÃ­culos"
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Etiquetas"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Header config
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = "/images/logo-ry.png"
      # title name
      name = ""
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = false
